### ISSUE TITLE
ModuleNotFoundError: No module named 'dash_core_components'

### ISSUE THREAD

**Issue by NTNguyen13** [plotly/dash-tsne#1]
I have install dash through conda-forge and clone the git. When I tried `python app.py` or `python3 app.py`
the error is:
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from demo import demo_layout, demo_callbacks
  File "/path/dash-tsne/demo.py", line 9, in <module>
    import dash_core_components as dcc
ModuleNotFoundError: No module named 'dash_core_components'

How can I fix this error?

**Comment by xhlulu** [comment]
Hey! Have you tried installing the required libraries from requirements.txt?

**Comment by NTNguyen13** [comment]
Yes, I installed and it worked, that's why I close the issue. I thought the dash_core_component is installed along with dash, but I was wrong. 

There's another problem: when I start app.py and upload the files, although it said OK, but after a while it said connection timed out. I'm pretty sure that I'm using the local version, because I won't be able to upload my data to demo.py. How can I fix that?

**Comment by xhlulu** [comment]
If the dataset didn't not upload correctly, then an error message should show up. However, if the dataset is too big, the app might indeed time out, since t-SNE takes a lot of time to compute bigger datasets.

Can you show a screenshot of what the error looks like on the app, and a log of the console output when the error happens?

**Comment by NTNguyen13** [comment]
Hi, here is the screenshot
![image](https://user-images.githubusercontent.com/39985901/43309495-e42f141a-91bf-11e8-914a-30e49c01ac53.png)

and the log:
* Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
* Restarting with stat
* Debugger is active! 
* Debugger PIN: 527-027-316
127.0.0.1 - - [27/Jul/2018 17:10:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:00] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:00] "GET /_ dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:00] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:00] "POST /_dash-update-component HTTP/1.1" 200 - 
127.0.0.1 - - [27/Jul/2018 17:11:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:02] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:02] "POST /_ dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:02] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2018 17:11:02] "POST /_dash-update-component HTTP/1.1" 200 -

My data has 200 rows and 150 columns

**Comment by xhlulu** [comment]
Is your data all numerical values? t-SNE doesn't support string labels.

There was likely an error when sklearn tried to process your dataset. It wasn't shown in console because of this: https://github.com/plotly/dash-tsne/blob/f6e5b45b64009a4ebfe75a8312a1579eb8c4b32c/local.py#L406

The try except here catches the timeout errors when the app is hosted on heroku, which is why the misleading error message is given. If you remove the try and except, you should be able to see why it wasn't processed, and try to find the error in the sklearn documentation for t-sne: http://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html

If there's anything abnormal, feel free to make a PR with the suggested changes! The local version of this app is a WIP, so any community contribution is welcome.

**Comment by NTNguyen13** [comment]
after removing the try - except, the error turned out to be `symbol = 'circle-dot'` , I changed it to `'circle'` and everything works well

**Comment by xhlulu** [comment]
Feel free to reopen if you find any other problem!
